spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mine_db?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1092982300

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082
